export const usLang = {
    "控制台": "Console",
    "更多": "Read More",
    "為何選擇我們": "Why cChoose Us",
    "我們的日常任務：查找並展示最佳網絡設計靈感和趨勢。 每天，我們都會發布由來自世界各地的創意機構和網頁設計師。": "Our daily task: find and show the best web design inspirations and trends. Every day, we publish it by creative agencies and web designers from all over the world.",
    "網頁設計與網站曝光的好壞是足以影響一家公司的整體業績，在網際網路興起後，除了網站本身以外，推廣曝光也是日趨重要，一個好的網頁設計公司，除了要能為企業規劃一個好網站，並且能持續建議後續網站的推廣方向，幫助客戶把費用花在刀口上，新視野於網頁設計產業兢兢業業持續十餘年努力，累積服務超過千家企業，對每個客戶都如同對自己事業一樣認真服務。": "The quality of web design and website exposure is enough to affect the overall performance of a company. After the rise of the Internet, in addition to the website itself, the promotion of exposure is also becoming more and more important. A good web design company must be able to plan for the company. It can continue to suggest the promotion direction of the follow-up website and help customers spend their money on the edge. New Vision has worked hard in the web design industry for more than ten years and has accumulated services for more than a thousand companies. It is as serious to each customer as it is to its own business. service.",
    "測試": "Test",
    "下載": "Download",
    "會員": "Member",
    "使用者": "User",
    "據點": "Place",
    "關於我們": "About",
    "團隊介紹": "Team Introduction",
    "品牌故事": "Brand Story",
    "相關單位": "Related Unit",
    "最新消息": "News",
    "最新公告": "Latest News",
    "相關消息": "Related News",
    "服務內容": "Service",
    "項目": "Project",
    "技能": "Skill",
    "作品": "Works",
    "價格": "Price",
    "聯絡我們": "Contact",
    "聯絡方式": "Contact Method",
    "發送建議": "Send Suggestion",
    "關於Nains的前端寫作能力非常出色，他是一個充滿智慧，技術和熱情的網頁設計師。": "About Nains's front-end writing ability is very good, he is a web designer full of wisdom, technology and enthusiasm.",
    "前端": "Front end",
    "關於Nains的前端寫作能力非常出色，他是非常優秀的人才，他是一個充滿智慧，技術和熱情的網頁設計師。": "About Nains's front-end writing ability is very good, he is a very good talent, he is a web designer full of wisdom, technology and enthusiasm.",
    "後端": "Back end",
    "關於Todd的後端寫作能力非常出色，他是非常優秀的人才，他是一個充滿智慧，技術和熱情的網頁設計師。": "About Todd's back-end writing ability is very good, he is a very good talent, he is a web designer full of wisdom, technology and enthusiasm.",
    "場所1": "Location 1",
    "台中市ＸＸ區ＸＸ路ＸＸ段ＸＸ號ＸＸ樓": "Building XX, Section XX, XX Road, XX District, Taichung City",
    "場所2": "Location 2",
    "台北市ＸＸ區ＸＸ路ＸＸ段ＸＸ號ＸＸ樓": "Building XX, Section XX, XX Road, XX District, Taipei City",
    "場所3": "Location 3",
    "高雄市ＸＸ區ＸＸ路ＸＸ段ＸＸ號ＸＸ樓": "Building XX, Section XX, XX Road, XX District, Kaohsiung City",
    "網頁": "WEB",
    "類別: ": "Type: ",
    "可通過以下方式聯繫我們，亦可直接發送信件給予我們建議。": "You can contact us in the following ways, or you can send us a letter directly to give us suggestions.",
    "一鍵複製": "One-click copy",
    "我們傾聽您的聲音": "We listen to you",
    "若您對產品、服務內容，有任何疑問或建議，煩請填寫個人資料，我們將儘速為您處理，謝謝！！": "If you have any questions or suggestions about the content of products and services, please fill in your personal information and we will handle it for you as soon as possible, thank you! !",
    "姓名": "Name",
    "郵箱": "mailbox",
    "給我們的建議": "Suggestions to us",
    "發送": "send",
    "我們將會盡快與您聯繫，一般於 當天 - 三天 的時間回覆。": "We will contact you as soon as possible, usually within three days of the same day.",
    "台中市西區": "Taichung City West District",
    "三民路一段50巷8號": "No. 8, Lane 50, Section 1, Sanmin Road",
    "我們所做的": "What We Do",
    "使用簡單的聲明性模板快速構建功能。 使用您自己的組件擴展模板語言，並使用各種各樣的現有組件。": "Use simple declarative templates to quickly build functionality. Extend the template language with your own components and use a variety of existing components.",
    "幾乎所有的IDE和編輯器都可立即獲得特定於Angular的幫助和反饋。": "Almost all IDEs and editors can get immediate help and feedback specific to Angular.",
    "所有這些結合在一起，因此您可以專注於構建出色的應用程序，而不是試圖使代碼正常工作。": "All of these come together so you can focus on building great applications instead of trying to make the code work.",
    "技能與分工": "Skills and division of labor",
    "我們的日常任務：查找並展示最佳網絡設計靈感和趨勢。": "Our daily task: find and show the best web design inspirations and trends.",
    "每天，我們都會發布由來自世界各地的創意機構和網頁設計師。": "Every day, we publish it by creative agencies and web designers from all over the world.",
    "方案": "Program",
    "使用簡單的聲明性模板快速構建功能。": "Use simple declarative templates to quickly build functionality.",
    "使用您自己的組件擴展模板語言，並使用各種各樣的現有組件。 幾乎所有的IDE和編輯器都可立即獲得特定於Angular的幫助和反饋。": "Extend the template language with your own components and use a variety of existing components. Almost all IDEs and editors can get immediate help and feedback specific to Angular.",
    "月繳": "Monthly",
    "年繳": "Annual",
    "可以花錢解決的事，千萬不要慢慢看": "Don’t take your time to look at things that can be solved with money",
    "最優惠": "Best prices",
    "買了啦": "Bought it",
    "不買會對不起國家": "I would not be able to afford the country",
    "近期作品": "Recent works",
    "溝通": "communication",
    "團隊合作": "teamwork",
    "項目管理": "project management",
    "創造力": "creativity",
    "月標題1": "Month title 1",
    "條件1": "Condition 1",
    "條件2": "Condition 2",
    "條件3": "Condition 3",
    "月標題2": "Month title 2",
    "條件4": "Condition 4",
    "月標題3": "Month title 3",
    "月標題4": "Month title 4",
    "年標題1": "Year title 1",
    "年標題2": "Year title 2",
    "年標題3": "Year title 3",
    "年標題4": "Year title 4",
    "全部": "All",
    "第一種": "first",
    "第二種": "second",
    "第三種": "third",
    "登入": "Sign In",
    "還沒有帳號": "don`t have an account",
    "註冊": "Sign Up",
    "已經有帳號了": "Already have an account",
    "帳號": "Username",
    "密碼": "Password",
    "信箱": "Email",
    "再次確認": "Double Confirm",
    "下一則": "Next",
    "用戶名": "UserName",
    "登陸時間": "Login time",
    "現有資料": "Existing information",
    "新增及更改資料": "Add and change information",
    "新增": "Add",
    "更改": "Change",
    "選取並刪除": "Select And Delete",
    "刪除": "Delete",
    "聯繫我們": "Contact Us",
    "優惠": "Discount",
    "系統": "System",
    "分工": "Division of labor",
    "月": "month",
    "年": "year",
    "建議已送出，我們將盡快與您聯繫!": "The suggestion has been sent, we will contact you as soon as possible!",
    "未能成功送出意見": "Unsuccessful submission of comments",
    "請務必填寫完整": "Please fill in completely",
    "信箱格式錯誤": "Mailbox format error",
    "已成功複製到剪貼簿": "Successfully copied to clipboard"
}